export const characters = {
    START_FETCH_CHARACTERS: 'START_FETCH_CHARACTERS',
    FETCH_CHARACTERS: 'FETCH_CHARACTERS',
    ERROR_FETCH_CHARACTERS: 'ERROR_FETCH_CHARACTERS',
    SEARCH_FILTER: 'SEARCH_FILTER'
};

export const login = {
    START_FETCH_LOGIN: 'START_FETCH_LOGIN',
    FETCH_LOGIN: 'FETCH_LOGIN',
    ERROR_FETCH_LOGIN: 'ERROR_FETCH_LOGIN',
    LOGOUT: 'LOGOUT',
    CHECK_LOGIN: 'CHECK_LOGIN'
};

export const register = {
    START_FETCH_REGISTER: 'START_FETCH_REGISTER',
    FETCH_REGISTER: 'FETCH_REGISTER',
    ERROR_FETCH_REGISTER: 'ERROR_FETCH_REGISTER'
};
